
# brief summary of what this code does (1-2 lines)

# INPUTS
# list of external data needed in the script, e.g.
# - dataframe of trait measurements: "data/bird_traits.csv"

# OUTPUTS
# list of results generated by this code, e.g.
# - dataframe of average trait values: "results/trait_metrics.csv"
# - figure of species counts: "results/figures/species_count.pdf"

# -------------------------------------------------------------------------
# dependencies - it is always good to be explicit about the packages
# needed in your code

library(tidyverse)

# -------------------------------------------------------------------------
# it is good practice to define in advance the input/output strings
# note that if you define dinamically the output names of your results, you 
# can do it here

input.file <- "data/bird_traits.csv"
output.file <- "results/traits_metrics.csv"

# -------------------------------------------------------------------------
# reading external data

# names should be concise but explanatory
# always follow the same convention (e.g. adv-r.had.co.nz/Style.html)

# I use points as space separators, just because it is quicker to type than
# underscores. 
# column names in df?
# function names?
bird.traits <- read.csv2()

# -------------------------------------------------------------------------
# data clean-up

# every modification to your raw data should be done programatically, 
# in order to spot and correct mistakes
# store the modified objects with a different name

bird.traits.clean <- subset(bird.traits)

# if you pick some code from the internet (e.g. stack overflow), it is advised
# to leave the reference in a comment, e.g.
# code adapted from http://...

# -------------------------------------------------------------------------
# output section

write.csv2(bird.traits.clean, output.file)


# -------------------------------------------------------------------------

# other stuff

# Rstudio projects
# folder organization - working directory
# function documentation
# naming scripts sequentially (00_a.R, 01_b.R, etc)
# tabular data *always* in open formats
# always comment code
# indent and spacing







