
# brief summary of what this code does

# INPUTS
# list of external data needed in the script, e.g.
# - dataframe of trait measurements: "data/bird_traits.csv"

# OUTPUTS
# list of results generated by this code, e.g.
# - dataframe of average trait values: "results/trait_metrics.csv"
# - figure of species counts: "results/figures/species_count.pdf"

# -------------------------------------------------------------------------
# dependencies - it is always good to be explicit about the packages
# needed in your code

library(tidyverse)
source("R/HandWingIndex.R")

# -------------------------------------------------------------------------
# somewhere at the beginning of the script there should be a section 
# where you define the variables to be used. Below this section, you should 
# ideally not have to enter any information "by hand".

c1 <- 13
c2 <- seq(1,10,by=.3)

# -------------------------------------------------------------------------
# it is good practice to define in advance the input/output strings
# note that if you define dinamically the output names of your results, you 
# can do it here

input.file <- "data/bird_traits.csv"
output.file <- paste("results/traits_metrics_",c1,".csv",sep="")

# -------------------------------------------------------------------------
# reading external data

# names should be concise but explanatory
# always follow the same convention (e.g. https://style.tidyverse.org/)

# I use points as space separators, just because it is quicker to type than
# underscores. 
# column names in df?
# function names?
bird.traits <- read.csv(input.file)

# -------------------------------------------------------------------------
# data clean-up

# every modification to your raw data should be done programatically, 
# in order to spot and correct mistakes
# store the modified objects with a different name

bird.traits.clean <- subset(bird.traits, BILL_LENGTH_mm > c1)

# if you pick some code from the internet (e.g. stack overflow), it is advised
# to leave the reference in a comment, e.g.
# code adapted from http://...
# likewise with references for specific functions
# hand-wing index function from https://www.nature.com/articles/s41467-020-16313-6
bird.traits.clean$HWI <- HandWingIndex(k = bird.traits.clean$DIST_OF_S1_TO_WING_TIP_cm,
                                       l = bird.traits.clean$WING_LENGTH_cm)

# -------------------------------------------------------------------------
# output section

write.csv2(bird.traits.clean, output.file)

# -------------------------------------------------------------------------

# other stuff

# Rstudio projects
# folder organization - working directory
# naming scripts sequentially (00_a.R, 01_b.R, etc)
# tabular data *always* in open formats
# always comment code
# indent and spacing
# keep yourself to 80 characters per line, if possible: split comments and 
# function calls if necessary
# never save the environment!






